name: H_1
on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup FFmpeg using versions
        uses: Iamshankhadeep/setup-ffmpeg@v1.2
        
      - name: Setup Environment
        run: |
          pip install --upgrade pip
          pip install Pillow pyscreenshot
          pip install -r ./requirements.txt


      - name: Install Warp
        continue-on-error: true
        run: |
          wget https://pkg.cloudflareclient.com/uploads/cloudflare_warp_2022_5_346_1_amd64_ea02be46df.deb -O warp.deb && sudo dpkg -i warp.deb || true ; sudo apt-get -f install -y 
          warp-cli --accept-tos register
          warp-cli --accept-tos connect
          warp-cli --accept-tos set-mode warp+doh && sleep 1s
        shell: bash
          
      - name: 'Renew'
        env:
          TITLE: ${{ secrets.TITLE_H_1 }}
          URL_BASE: ${{ secrets.URL_BASE_H }}
          USERNAME: ${{ secrets.USERNAME_H_1 }}
          PASSWORD: ${{ secrets.PASSWORD_H_1 }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |  
          xvfb-run python3 ./main.py
